// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StayEasy.DataAccess.Contexts;

#nullable disable

namespace StayEasy.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106101511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StayEasy.Domain.Entities.BaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator().HasValue("BaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Booking", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Booking");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Favorites", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PropertyId")
                        .IsUnique();

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("PropertyId")
                                .HasColumnName("Favorites_PropertyId");

                            t.Property("UserId")
                                .HasColumnName("Favorites_UserId");
                        });

                    b.HasDiscriminator().HasValue("Favorites");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Message", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("PropertyId")
                                .HasColumnName("Message_PropertyId");
                        });

                    b.HasDiscriminator().HasValue("Message");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Notifications", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("ReleatedEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Content")
                                .HasColumnName("Notifications_Content");

                            t.Property("IsRead")
                                .HasColumnName("Notifications_IsRead");

                            t.Property("UserId")
                                .HasColumnName("Notifications_UserId");
                        });

                    b.HasDiscriminator().HasValue("Notifications");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Payments", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("UserId")
                                .HasColumnName("Payments_UserId");
                        });

                    b.HasDiscriminator().HasValue("Payments");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.PropertyAmenities", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasIndex("PropertyId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("PropertyId")
                                .HasColumnName("PropertyAmenities_PropertyId");
                        });

                    b.HasDiscriminator().HasValue("PropertyAmenities");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.PropertyImageUrl", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasIndex("Order");

                    b.HasIndex("PropertyId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("PropertyId")
                                .HasColumnName("PropertyImageUrl_PropertyId");
                        });

                    b.HasDiscriminator().HasValue("PropertyImageUrl");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Propertys", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("Category");

                    b.HasIndex("City");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("District");

                    b.HasIndex("Price");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("Status")
                                .HasColumnName("Propertys_Status");

                            t.Property("Title")
                                .HasColumnName("Propertys_Title");

                            t.Property("Type")
                                .HasColumnName("Propertys_Type");

                            t.Property("UserId")
                                .HasColumnName("Propertys_UserId");
                        });

                    b.HasDiscriminator().HasValue("Propertys");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Reviews", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Response")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("BaseEntity", t =>
                        {
                            t.Property("BookingId")
                                .HasColumnName("Reviews_BookingId");

                            t.Property("PropertyId")
                                .HasColumnName("Reviews_PropertyId");

                            t.Property("UserId")
                                .HasColumnName("Reviews_UserId");
                        });

                    b.HasDiscriminator().HasValue("Reviews");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.User", b =>
                {
                    b.HasBaseType("StayEasy.Domain.Entities.BaseEntity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("Role");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Booking", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.Propertys", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayEasy.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Favorites", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.Propertys", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayEasy.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Message", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.Propertys", "Property")
                        .WithMany("Messages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StayEasy.Domain.Entities.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StayEasy.Domain.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Notifications", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Payments", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("StayEasy.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.PropertyAmenities", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.Propertys", "Propertys")
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propertys");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.PropertyImageUrl", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.Propertys", "Propertys")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propertys");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Propertys", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Reviews", b =>
                {
                    b.HasOne("StayEasy.Domain.Entities.Booking", "Booking")
                        .WithOne("Reviews")
                        .HasForeignKey("StayEasy.Domain.Entities.Reviews", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayEasy.Domain.Entities.Propertys", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayEasy.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.Propertys", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Messages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("StayEasy.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Properties");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("Reviews");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
